### ISSUE TITLE
Unable to use this module

### ISSUE THREAD

**Issue by Aruna-99** [Ingenico-ePayments/connect-sdk-client-js-example#1]
Hi Team,

I am getting the following error...for all actions you provided

{
  "errno": "ENOTFOUND",
  "code": "ENOTFOUND",
  "syscall": "getaddrinfo",
  "hostname": "https://eu.preprod.api-ingenico.com",
  "host": "https://eu.preprod.api-ingenico.com",
  "port": 443
}

I have provided all necessary things called MerchantID, ApiKey and ApiSecret also..

I am unable to figured it out from last 24 hrs.. Please can anyone help me on this,

Thanks in Advance...

**Comment by rob-spoor** [comment]
From https://stackoverflow.com/questions/23259697/error-getaddrinfo-enotfound-in-nodejs-for-get-call

> getaddrinfo ENOTFOUND means client was not able to connect to given address

I have checked the hostname that is reported, and it is working just fine. Perhaps there is an issue with your local infrastructure. Can you try calling https://eu.preprod.api-ingenico.com from the machine you get this error on? That should give a 404 response, but that at least means you can connect.

**Comment by Maaverick** [comment]
Same issue here and solved, you have to fill the host propertie in this way, host: 'eu.preprod.api-ingenico.com'. I admit it's a bit confusing when ingenico redirect you to their endpoints page starting with https://, and you make a lazy copy/paste :p
